### ISSUE TITLE
is wither a PhantomJS app?

### ISSUE THREAD

**Issue by slothbear** [pickaxe-club/wither#20]
Deploying to Heroku, PhantomJS "detected".

```
remote: -----> PhantomJS app detected        
remote: -----> Extracting PhantomJS 2.1.1 binaries to /tmp/build_2b27bb68/vendor/phantomjs        
```

This is probably some default, or perhaps a mistaken identity from some setting. I see no ill effects, but we're probably more of a ruby app.

**Comment by tyrosinase** [comment]
There used to be PhantomJS in it (if you search through old commits) but that's long gone. It must live on in some config somewhere.

**Comment by slothbear** [comment]
The old commits suggest that PhantomJS was part of a map feature. The app still has the PhantomJS buildpack.

```
heroku buildpacks
=== wither Buildpack URLs
1. heroku/ruby
2. https://github.com/stomita/heroku-buildpack-phantomjs
```

I'll remove that sometime and monitor to make sure stuff still works..

**Comment by slothbear** [comment]
I'm trying to explore new features via the Heroku console — which currently launches the PhantomJS repl. Perhaps there is a way to select a console, but since we don't need PhantomJS, seems like a good time to get rid of it. Log below. 

`heroku console` now launches irb. 🥇 

```
heroku buildpacks
=== wither Buildpack URLs
1. heroku/ruby
2. https://github.com/stomita/heroku-buildpack-phantomjs

heroku buildpacks:remove https://github.com/stomita/heroku-buildpack-phantomjs
Buildpack removed. Next release on wither will use heroku/ruby.
Run git push heroku main to create a new release using this buildpack.
```
